name: Build and Run Windows FileID

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Setup MSVC environment
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build with MSVC
        run: cl windows_fileid.c

      - name: Create test file
        run: echo Hello > myfile.txt

      - name: Run the program
        run: .\windows_fileid.exe

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows_fileid
          path: windows_fileid.exe
